const ACTION_TYPE = {
    PARTICIPANT:{
        ADD: 'ADD_PARTICIPANT',
        INJECT_HARDCODED_DATA: 'INJECT_HARDCODED_DATA',
        REMOVE: 'REMOVE_PARTICIPANT',
        UPDATE_COUNT: 'UPDATE_COUNT'
    },
    MAINPOT:{
        SAVE_SUM: 'SAVE_MAINPOT_CONTRIB_AMOUNT'
    },
    SIDEPOT:{
        ADD_SIDEPOT: 'ADD_SIDEPOT',
        SAVE_SUM: 'SAVE_SIDEPOT_CONTRIB_AMOUNT',
        SAVE_PARTICIPANTS: 'SAVE_SIDEPOT_PARTICIPANTS',
    }
}

export default ACTION_TYPE;